export const nationFlags = {
  USA: 'https://flagcdn.com/w40/us.png',
  Russia: 'https://flagcdn.com/w40/ru.png',
  Germany: 'https://flagcdn.com/w40/de.png',
  Norway: 'https://flagcdn.com/w40/no.png',
  Canada: 'https://flagcdn.com/w40/ca.png',
  Sweden: 'https://flagcdn.com/w40/se.png',
  Austria: 'https://flagcdn.com/w40/at.png',
  Switzerland: 'https://flagcdn.com/w40/ch.png',
  Finland: 'https://flagcdn.com/w40/fi.png',
  Netherlands: 'https://flagcdn.com/w40/nl.png',
  France: 'https://flagcdn.com/w40/fr.png',
  Italy: 'https://flagcdn.com/w40/it.png',
  China: 'https://flagcdn.com/w40/cn.png',
  Japan: 'https://flagcdn.com/w40/jp.png',
  'South Korea': 'https://flagcdn.com/w40/kr.png',
  'Czech Republic': 'https://flagcdn.com/w40/cz.png',
  'Great Britain': 'https://flagcdn.com/w40/gb.png',
  Slovenia: 'https://flagcdn.com/w40/si.png',
  Poland: 'https://flagcdn.com/w40/pl.png',
  Belarus: 'https://flagcdn.com/w40/by.png',
  Australia: 'https://flagcdn.com/w40/au.png',
  Croatia: 'https://flagcdn.com/w40/hr.png',
  Hungary: 'https://flagcdn.com/w40/hu.png',
  Liechtenstein: 'https://flagcdn.com/w40/li.png',
  Latvia: 'https://flagcdn.com/w40/lv.png',
  Slovakia: 'https://flagcdn.com/w40/sk.png',
  Ukraine: 'https://flagcdn.com/w40/ua.png',
  Belgium: 'https://flagcdn.com/w40/be.png',
  Kazakhstan: 'https://flagcdn.com/w40/kz.png',
  Estonia: 'https://flagcdn.com/w40/ee.png',
  Bulgaria: 'https://flagcdn.com/w40/bg.png',
  'New Zealand': 'https://flagcdn.com/w40/nz.png',
  Brazil: 'https://flagcdn.com/w40/br.png',
  Georgia: 'https://flagcdn.com/w40/ge.png',
  Spain: 'https://flagcdn.com/w40/es.png',
  Yugoslavia: '/flags/yugoslavia.svg',
  'North Korea': 'https://flagcdn.com/w40/kp.png',
  Luxembourg: 'https://flagcdn.com/w40/lu.png',
  Romania: 'https://flagcdn.com/w40/ro.png',
  Uzbekistan: 'https://flagcdn.com/w40/uz.png',
  Denmark: 'https://flagcdn.com/w40/dk.png',
  Czechoslovakia: '/flags/czechoslovakia.svg',
  'East Germany': '/flags/gdr.svg',
  'West Germany': 'https://flagcdn.com/w40/de.png',
  'United Team of Germany': '/flags/eua.svg',
  'Soviet Union': '/flags/ussr.svg',
  'Unified Team': '/flags/olympic.svg',
  'Olympic Athletes from Russia': '/flags/olympic.svg',
  ROC: '/flags/olympic.svg',
  'Individual Neutral Athletes': '/flags/olympic.svg',
}
